// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Salarylookup.Api.Data;

namespace Salarylookup.Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Salarylookup.Api.Models.Salary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Annual_Base_Salary");

                    b.Property<string>("Department");

                    b.Property<string>("Ethnicity");

                    b.Property<string>("First_Name");

                    b.Property<double>("Hourly_Rate");

                    b.Property<string>("Last_Name");

                    b.Property<string>("Middle_Name");

                    b.Property<string>("Organization");

                    b.Property<string>("Race");

                    b.Property<char>("Sex");

                    b.Property<string>("Spirit_Animal");

                    b.Property<string>("Title");

                    b.Property<string>("Vp_College");

                    b.HasKey("Id");

                    b.ToTable("Salaries");
                });
#pragma warning restore 612, 618
        }
    }
}
